export const IPC_CHANNELS = {
  FILE_READ: 'file:read',
  FILE_WRITE: 'file:write',
  FILE_DELETE: 'file:delete',
  FILE_LIST: 'file:list',
  FILE_LIST_ENTRY: 'file:list-entry',
  FILE_LIST_DONE: 'file:list-done',
  FILE_SCAN_PROGRESS: 'file:scan-progress',
  FILE_CHANGED: 'file:changed',
  FILE_SEARCH: 'file:search',
  FILE_REPLACE: 'file:replace',
  PROJECT_OPEN: 'project:open',
  PROJECT_SET: 'project:set',
  PROJECT_RECENT: 'project:recent',
  // AI session management
  AI_START_SESSION: 'ai:start-session',
  AI_SEND: 'ai:send',
  AI_INTERRUPT: 'ai:interrupt',
  // AI streaming (structured)
  AI_CONTENT_BLOCK_START: 'ai:content-block-start',
  AI_TEXT_DELTA: 'ai:text-delta',
  AI_THINKING_DELTA: 'ai:thinking-delta',
  AI_CONTENT_BLOCK_STOP: 'ai:content-block-stop',
  // AI tool calls
  AI_TOOL_USE: 'ai:tool-use',
  AI_TOOL_PROGRESS: 'ai:tool-progress',
  AI_TOOL_USE_SUMMARY: 'ai:tool-use-summary',
  AI_TOOL_RESULT: 'ai:tool-result',
  AI_TOOL_CONFIRM: 'ai:tool-confirm',
  AI_TOOL_DESCRIPTION: 'ai:tool-description',
  AI_CONFIRM_TOOL: 'ai:confirm-tool',
  // AI lifecycle
  AI_TURN_COMPLETE: 'ai:turn-complete',
  AI_STATUS: 'ai:status',
  AI_INIT: 'ai:init',
  AI_RESULT: 'ai:result',
  AI_ERROR: 'ai:error',
  AI_COMMANDS_LOADED: 'ai:commands-loaded',
  AI_GET_COMMANDS: 'ai:get-commands',
  // Backward compat
  AI_DELTA: 'ai:delta',
  AI_CANCEL: 'ai:cancel',
  AI_ANSWER_QUESTION: 'ai:answer-question',
  // Chat persistence
  CHAT_LIST_CONVERSATIONS: 'chat:list-conversations',
  CHAT_SAVE_CONVERSATION: 'chat:save-conversation',
  CHAT_DELETE_CONVERSATION: 'chat:delete-conversation',
  CHAT_GET_CONVERSATION: 'chat:get-conversation',
  CHAT_GENERATE_TITLE: 'chat:generate-title',
  // Terminal
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_DATA: 'terminal:data',
  // Config
  CONFIG_GET_PROFILES: 'config:get-profiles',
  CONFIG_GET_ACTIVE_PROFILE: 'config:get-active-profile',
  CONFIG_SET_ACTIVE_PROFILE: 'config:set-active-profile',
  CONFIG_CREATE_PROFILE: 'config:create-profile',
  CONFIG_UPDATE_PROFILE: 'config:update-profile',
  CONFIG_DELETE_PROFILE: 'config:delete-profile',
  CONFIG_LOAD_CLAUDE_SETTINGS: 'config:load-claude-settings',
  CONFIG_GET_MCP_SERVERS: 'config:get-mcp-servers',
  CONFIG_SAVE_MCP_SERVERS: 'config:save-mcp-servers',
  // Format
  CONFIG_FORMAT_DOCUMENT: 'config:format-document',
  CONFIG_GET_FORMAT_SETTINGS: 'config:get-format-settings',
  CONFIG_SET_FORMAT_SETTINGS: 'config:set-format-settings',
  // Locale
  CONFIG_GET_LANGUAGE: 'config:get-language',
  CONFIG_SET_LANGUAGE: 'config:set-language',
  LOCALE_CHANGED: 'locale:changed',
  // Session
  SESSION_SAVE: 'session:save',
  SESSION_RESTORE: 'session:restore',
  DIALOG_OPEN_FILES: 'dialog:open-files',
  AI_INLINE_COMPLETE: 'ai:inline-complete',
  AI_REVIEW_CODE: 'ai:review-code',
  AI_GET_CONTEXT_USAGE: 'ai:get-context-usage',
  FILE_WRITE_BINARY: 'file:write-binary',
  SFTP_CONNECT: 'sftp:connect',
  SFTP_DISCONNECT: 'sftp:disconnect',
  SFTP_STATUS: 'sftp:status',
  GIT_STATUS: 'git:status',
  GIT_DIFF: 'git:diff',
  GIT_DIFF_STAGED: 'git:diff-staged',
  GIT_STAGE: 'git:stage',
  GIT_UNSTAGE: 'git:unstage',
  GIT_COMMIT: 'git:commit',
  GIT_BRANCHES: 'git:branches',
  GIT_CHECKOUT: 'git:checkout',
  GIT_PULL: 'git:pull',
  GIT_PUSH: 'git:push',
  GIT_LOG: 'git:log',
  SVN_STATUS: 'svn:status',
  SVN_DIFF: 'svn:diff',
  SVN_ADD: 'svn:add',
  SVN_REVERT: 'svn:revert',
  SVN_COMMIT: 'svn:commit',
  SVN_UPDATE: 'svn:update',
  SVN_INFO: 'svn:info',
} as const;

export const PERMISSION_LEVEL = {
  AUTO: 0,
  CONFIRM: 1,
  APPROVE: 2,
} as const;

export const DANGEROUS_COMMAND_PATTERNS = [
  /rm\s+-rf\s+\//,
  /git\s+push\s+--force/,
  /DROP\s+TABLE/i,
  /DELETE\s+FROM/i,
  /sudo\s+/,
] as const;
